=== swifiic/repo/hub/plat/app/soa/hub/src/meta-data/schema/AppHub.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema attributeFormDefault="unqualified" 
                elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="AppDef">

    <xs:complexType>
       <xs:sequence>
       	 <xs:element name="rolesNeeded" maxOccurs="3" type="RoleType">
      		<xs:annotation>
      			<xs:documentation>
      				Types of roles users can have
      			</xs:documentation>
      		</xs:annotation>
      	 </xs:element>


      	<!--
      		1.  Name: UserMgtApp
      		2.  Version: 0.1
      		3.  Roles: Operator
      		4.  User ID Mapping to roles: Out of band / hard coded
      		5.  Role Billing Paradigm: Monthly
      		6.  Role Visibility: None
      		7.  Audit Visibility: Private
      		8.  Number of activities
      		
      		Behavioral Notes: 
      		- All activities are “Synchronous” and need except Login, they need Client-State to be Authenticated.
      		- Server will only allow one Login for User Management App at a time.
      		- Client device App may not enforce password every time – it may trigger logins behind the scene on launch or may   prompt for password – if App settings demand so.
      		
      	-->

      	 <xs:element name="activity" minOccurs="0" type="Operations" maxOccurs="unbounded"/>
      	 <xs:element name="notification" minOccurs="0" type="Operations" maxOccurs="unbounded"/>
       </xs:sequence>

	   <xs:attribute type="xs:string" name="appName" use="required"/>
	   <xs:attribute type="xs:string" name="appVer" use="required"/>
	   <xs:attribute type="xs:string" name="appId" use="required"/>
	   <xs:attribute type="Billing" name="defBilling" />
	   <xs:attribute type="Visibility" name="roleVisibility" />
	   <xs:attribute type="Visibility" name="logVisibility" />

    </xs:complexType>
</xs:element> <!-- name="AppDef" -->



<xs:element name="PDU">
  <xs:complexType>   <!-- is it really needed? -->
     <xs:choice>
              <!-- to add 
              o Max Delay - In future may move to DTN PDU
              o Max Expected Cost - In future may move to DTN PDU
              o Client State: Authenticated, Don’t Care // optional - TBD
              o Ledger_Entry_Id request, commit; - TBD
              o Response_Code: Accept/Reject/UserPending/DeliveryPending/ optional - for request
              o Response_Context: Reject Reason (badArgs, invalidContext, badVer, permDenied…), 
              o Number of Arguments: can be intuitively decoded based on appId, activityId
              o Cost Paradigm
               -->
            
      	 <xs:element name="activity" minOccurs="0" type="Operations" maxOccurs="unbounded"/>
      	 <xs:element name="notification" minOccurs="0" type="Operations" maxOccurs="unbounded"/>

     </xs:choice>

	   		       <xs:attribute type="xs:string" name="version" use="required" />
	   		            <!--  Protocol id for AppHub - for backward compatability -->
	   		       
	   		       <xs:attribute type="xs:string" name="userId" use="required" />
	   		             <!--  userId(alphanum)/AccountNum -->

	   		       <xs:attribute type="xs:string" name="deviceId" use="required"/> <!-- Hostname(dtn://...) -->
	   		       
	   		       <xs:attribute type="xs:string" name="appId" use="required"/>
	   		       		<!-- Pre-configured Name for App / AppHub Module (alphanum) -->

	   		       <xs:attribute type="xs:string" name="appVer" use="required"/>
	   		       		<!-- To handle app upgrades -->
	   		       
	   		       
	   		       <xs:attribute type="Billing" name="billing" />

	   		       <xs:attribute type="Visibility" name="pduLogVisibility" />
    </xs:complexType>
 </xs:element> <!-- name="PDUDef" -->


  <xs:simpleType name="RoleType">
  	<xs:restriction base="xs:string">
      <xs:enumeration value="Admin"/>   <!-- only for AppHub Admins -->
      <xs:enumeration value="Operator"/> <!-- also for type Provider -->
      <xs:enumeration value="User"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Billing">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Monthly"/>   
      <xs:enumeration value="None"/> <!-- aka free -->
      <xs:enumeration value="PerEvent"/>
      <xs:enumeration value="Low"/>
      <xs:enumeration value="Medium"/>
      <xs:enumeration value="High"/>
      <!-- TBD daily, per minute etc. -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Visibility">
    <xs:restriction base="xs:string">
      <xs:enumeration value="OperatorOnly"/> <!-- Operator will see all -->   
      <xs:enumeration value="Admin"/> 
      <xs:enumeration value="AdminAndUser"/> <!-- either sender or receiver -->
      <xs:enumeration value="AdminAndCreator"/> <!-- only the sender - not the receivers -->
      <xs:enumeration value="User"/> <!-- Operator and User making the call / involved in the call -->
      <xs:enumeration value="Public"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="OperationMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SyncOperator"/> <!--  highest priority - need to be at App Hub delay within 100 msec -->
      <xs:enumeration value="SyncApp"/>   
      <xs:enumeration value="AsyncBestEffort"/> <!-- least priority - OK to loose -->
      <xs:enumeration value="AsyncNotifyAndAck"/> <!-- user notification / app notification - returning Ack is Best Effort -->
      <xs:enumeration value="AsyncNotifyNoAck"/>  <!-- user notification / app notification - sender does not wait on Ack --> 
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="DelayType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Critical"/>
      <xs:enumeration value="HiPri"/>
      <xs:enumeration value="MedPri"/>
      <xs:enumeration value="LowPri"/> 
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="DiscardType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="OnlyOnDeliveryOrTimeout"/> <!-- or ack of delivery -->
      <xs:enumeration value="OnLowSpaceWarnThreshold"/>
      <xs:enumeration value="OnLowCriticalThreshold"/> 
    </xs:restriction>
  </xs:simpleType>

       

  <xs:complexType name="Operations">
      <xs:sequence>
           
           <xs:element name="argument" minOccurs="0" maxOccurs="32">
             <xs:complexType>
	           <xs:attribute type="xs:string" name="argName"/>
    	       <xs:attribute type="xs:string" name="argValue"/>
    	       <xs:attribute type="xs:boolean" name="optional"/>
    	       <xs:attribute type="xs:boolean" name="output"/>
    	     </xs:complexType>
           </xs:element>
           
           <xs:element name="fileData" type="xs:base64Binary" minOccurs="0" maxOccurs="1"/>
           <!-- ref: http://www.xml.com/pub/a/98/07/binary/binary.html other option is xs:hexBinary -->
           
           
           <xs:element name="behavior" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation>Behavioral Notes / how to deal with in / out arguments etc.</xs:documentation>
                </xs:annotation>
           </xs:element>
           
      </xs:sequence>
           <xs:attribute name="name" type="xs:string" use="required"/>
           <xs:attribute name="mode" type="OperationMode" />
           <xs:attribute name="delay" type="DelayType" />
           <xs:attribute name="discradPolicy" type="DiscardType" />
           <xs:attribute name="logVisibility" type="Visibility" />
           <xs:attribute name="operationAccess" type="Visibility" />
           <xs:attribute name="billing" type="Billing" />
           <xs:attribute name="coupledOperations" type="xs:string" >
                <xs:annotation>
                  <xs:documentation>
                      Comma separated list for operation that causes this to be 
                      triggered and operation that will be triggered by this.
                      If more than one operation are involved, they are pipe (|) separated.
                  </xs:documentation>
                </xs:annotation>
           </xs:attribute> <!-- if an activity causes a subsequent notification -->
  </xs:complexType>
  




</xs:schema>

=== swifiic/repo/plat/app/soa/hub/src/meta-data/schema/OprtrApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<AppDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="AppHub.xsd"
    appName="Oprtr" appVer="0.1" 
    defBilling="None" appId="2" 
    logVisibility="OperatorOnly" roleVisibility="Public">
    
  <rolesNeeded>Operator</rolesNeeded>
  <rolesNeeded>User</rolesNeeded>
  
  <activity name="Login" mode="SyncOperator" operationAccess="User">
      <argument argName="sessionId" argValue="cleints's nonce - post encryption with servers public key" />
      <argument argName="secret" argValue="shared secret - hash value - with key as sessionId" />
      <behavior>shared secret to be configured per device, sessionId should be pseudo random from client</behavior>
  </activity>

  <activity name="Logout" mode="SyncOperator" operationAccess="User">
      <argument argName="sessionId" argValue="cleints's nonce till logout - post encryption with servers public key" />
  </activity>
    
  <activity name="AddUser" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="usrEmail" argValue="Email Address - optional" />
      <argument argName="usrName" argValue="Complete Name" />
      <argument argName="address" argValue="Complete Address" />
      <argument argName="notes" argValue="Notes for user creation" />
      <argument argName="initialCredit" argValue="amount to be credited to user's account (numeric string)" />
      <argument argName="photoFileId" argValue="fileId assigned for photo file upload" optional="true" />
      <argument argName="idProofFileId" argValue="fileId assigned for idProof scan file upload" optional="true" />
      <argument argName="addressProofFileId" argValue="fileId assigned for address scan file upload" optional="true" />
      <argument argName="deviceId" argValue="unique ID for device (MAC of first interface)" optional="true" />
      <behavior>To provision the user for first time</behavior>
  </activity>
  
  <activity name="DeleteUser" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <behavior>To desable user account - records to be mantained as per audit policies</behavior>
  </activity>

  <activity name="RechargeUser" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="additionalCredit" argValue="amount to be added (deleted for -ve)(numeric string)" />
      <behavior>To provision the user for first time</behavior>
  </activity>
  

  <activity name="UpdateUserAddress" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="address" argValue="Complete Address" optional="true" />
      <argument argName="addressProofFileId" argValue="fileId assigned for address scan file upload" optional="true" />
      <argument argName="notes" argValue="Notes for user details change" />
      <behavior>To update address and address Proof</behavior>
  </activity>
  
  <activity name="UpdateUserDetails" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="photoFileId" argValue="fileId assigned for photo file upload" optional="true" />
      <argument argName="idProofFileId" argValue="fileId assigned for idProof scan file upload" optional="true" />
      <argument argName="notes" argValue="Notes for user details change" />
      <behavior>To upload new images proof etc.</behavior>
  </activity>

  <activity name="UpdateDevice" mode="SyncOperator" operationAccess="OperatorOnly">
      <argument argName="mobNum" argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="deviceId" />
      <argument argName="deviceName" />
      <argument argName="delete" argValue="true if device needs to be removed" optional="true" />
      <behavior>To add/delete device for a user account</behavior>
  </activity>

  <activity name="LookupUser" mode="SyncOperator" operationAccess="User">
      <argument argName="mobNum"   argValue="+91... Mobile number - for SMS etc. in future" />
      <argument argName="usrName"         output="true" />
      <argument argName="address"         output="true" />
      <argument argName="notes"           output="true" /> <!-- show only for Operator -->
      <argument argName="remainingCredit" output="true" />
      <argument argName="photoFileId"     output="true" />
      <argument argName="idProofFileId"   output="true" />
      <argument argName="addressProofFileId"  output="true" />
      <argument argName="deviceIds"       output="true" />
      <argument argName="deviceNames"     output="true" />
      <argument argName="appIds"          output="true" />
      <behavior>if queried by User some fields will be made blank/ all fields to be exposed for Operator.</behavior>
  </activity>
  
  <activity name="GetUserApps" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum"   argValue="+91... Mobile number" />
      <argument argName="appIds"         output="true" />
      <argument argName="appNames"       output="true" />
      <argument argName="appRoles"       output="true" /> 
      <argument argName="newAppIds"      output="true" />
      <argument argName="newAppNames"    output="true" />
      <behavior>List of apps used by user, and not used by user
          appIds and appRoles are comma separated ",". If multiple roles (should be allow it) - then "|" separated.</behavior>
  </activity>

  <activity name="GetAppDetails" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum"   argValue="+91... Mobile number" />
      <argument argName="appId"   argValue="id of the app learned previously" />
      <argument argName="appName"       output="true" />
      <argument argName="appRoles"      output="true" /> 
      <argument argName="appUsers"      output="true" />
      <argument argName="subscription"  output="true" /> 
      <behavior>appUsers is a list of comma separated values like "mobNum | role | name"
          if user is not subscribed to the app, it may not be able to see the Users
          subscription has details like "free" "monthly" or "per-event" etc. based on App definition.</behavior>
  </activity>
  
  <activity name="UpdateUserAppRole" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum" argValue="+91" />
      <argument argName="appId" />
      <argument argName="role" />
      <argument argName="delete" argValue="true if device needs to be removed" optional="true" />
      <behavior>To add/delete device for a user account</behavior>
  </activity>
  
  <activity name="GetBillDetails" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum"   argValue="+91... Mobile number" />
      <argument argName="concise"   argValue="false if detailed bill needed" optional="true" />
      <argument argName="billDetails"      output="true" /> 
      <behavior>To add/delete device for a user account</behavior>
  </activity>

  <activity name="DeliveryUpdate" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum"   argValue="+91... Mobile number" />
      <argument argName="deviceId"   />
      <argument argName="sessionId"  /> 
      <argument argName="appId"  /> 
      <argument argName="operation"  /> 
      <argument argName="status"  /> 
      <argument argName="notes"  /> 
      <argument argName="deviceLogId"  /> 
      <behavior>To confirm the delivery or similar status on device for notification etc.</behavior>
  </activity>
  
  
  <!--  TBD notifications -->
  <notification name="SyncDevice" mode="AsyncBestEffort" operationAccess="User">
      <argument argName="mobNum"       argValue="+91... Mobile number" />
      <argument argName="deviceId" />
      <argument argName="secretId"     argValue="new secret assigned to device for DTN, encrypted with pre-shared secret"/>
      <argument argName="validity"     argValue="expiry date for secret (possibly 2 days)"/>
      <argument argName="auditIds"     argValue="comma separated list of 2-5 recently processed Session/DTN Ids."/>
      
      <argument argName="syncSignature"   argValue="authenticity proof for the notification" />
      <argument argName="textSignature"      argValue="remaining credit, rating, last two billing event times etc." /> 
      <argument argName="syncText"      argValue="remaining credit, rating, issue time." /> 
      <behavior>syncSignature covers all except syncText; textSignature covers syncText</behavior>
  </notification>
  
</AppDef>

=== swifiic/repo/plat/app/soa/hub/src/meta-data/schema/MsngrAppDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<AppDef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="AppHub.xsd"
    appName="Msngr" appVer="0.1" 
    defBilling="Monthly" appId="2" 
    logVisibility="AdminAndUser" roleVisibility="Public">
    
  <rolesNeeded>Admin</rolesNeeded>
  <rolesNeeded>User</rolesNeeded>
  
  <activity name="SendMessage" delay="MedPri" 
      discradPolicy="OnLowSpaceWarnThreshold"  coupledOperations="DeliverMessage"
      mode="AsyncNotifyAndAck">
      <argument argName="message" argValue="user message to be sent" />
      <argument argName="userList" argValue="comma (,) separated user list; * for all" />
    <behavior>Only Admin can send message to all users</behavior>
  </activity>

  <activity name="DeliverReceipt" delay="LowPri" 
      discradPolicy="OnLowSpaceWarnThreshold" coupledOperations="SendMessage,DeliverReceipt" 
      mode="AsyncNotifyNoAck">
    <argument argName="message" argValue="user message that was sent" />
    <argument argName="sender" argValue="user message to be delivered" />
    <behavior>Receiver is interpreted from PDU</behavior>
  </activity>
  
  <notification name="DeliverMessage" delay="LowPri" 
      discradPolicy="OnLowSpaceWarnThreshold"  coupledOperations="SendMessage,DeliverReceipt"
      mode="AsyncNotifyAndAck">
      <argument argName="message" argValue="user message to be delivered" />
      <argument argName="sender" argValue="user message to be delivered" />
    <behavior>AppHub transforms SendMessage to DeliverMessage and sends to each entity specified in userList</behavior>
  </notification>
  
</AppDef>
